### ISSUE TITLE
CI build PR validation: support multi-repo PR

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-quickstarts#6]
A multi-repo PR adds APIs on timefold-solver that are used by the timefold-quickstarts PR
As a result, the quickstarts PR needs to be tested against the **adjusted** timefold-solver build.

See .github/workflwos/pull_request.yml

Proposal A) "Git modules" approach

Proposal B) Checkout the correct fork/branch for timefold-solver before building it:

```
    steps:
      - name: Checkout timefold-solver
        uses: actions/checkout@v3
        with:
          path: 'timefold-solver'
          repository: 'TimefoldAI/timefold-solver'

      - name: Checkout timefold-quickstarts
        uses: actions/checkout@v3
        with:
          path: 'timefold-quickstarts'
```
